/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet struct for ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet
type ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet struct {
	CacheTestErrorResponse    *CacheTestErrorResponse
	CacheTestFoundResponse    *CacheTestFoundResponse
	CacheTestNotFoundResponse *CacheTestNotFoundResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) UnmarshalJSON(data []byte) error {
	var err error
	*dst = ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet{}
	var value interface{}
	if err = json.Unmarshal(data, &value); err != nil {
		return err
	}
	if value == nil {
		return fmt.Errorf("null is not valid for ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet")
	}
	// try to unmarshal JSON data into CacheTestErrorResponse
	err = json.Unmarshal(data, &dst.CacheTestErrorResponse)
	if err == nil {
		jsonCacheTestErrorResponse, _ := json.Marshal(dst.CacheTestErrorResponse)
		if string(jsonCacheTestErrorResponse) == "{}" { // empty struct
			dst.CacheTestErrorResponse = nil
		} else {
			return nil // data stored in dst.CacheTestErrorResponse, return on the first match
		}
	} else {
		dst.CacheTestErrorResponse = nil
	}

	// try to unmarshal JSON data into CacheTestFoundResponse
	err = json.Unmarshal(data, &dst.CacheTestFoundResponse)
	if err == nil {
		jsonCacheTestFoundResponse, _ := json.Marshal(dst.CacheTestFoundResponse)
		if string(jsonCacheTestFoundResponse) == "{}" { // empty struct
			dst.CacheTestFoundResponse = nil
		} else {
			return nil // data stored in dst.CacheTestFoundResponse, return on the first match
		}
	} else {
		dst.CacheTestFoundResponse = nil
	}

	// try to unmarshal JSON data into CacheTestNotFoundResponse
	err = json.Unmarshal(data, &dst.CacheTestNotFoundResponse)
	if err == nil {
		jsonCacheTestNotFoundResponse, _ := json.Marshal(dst.CacheTestNotFoundResponse)
		if string(jsonCacheTestNotFoundResponse) == "{}" { // empty struct
			dst.CacheTestNotFoundResponse = nil
		} else {
			return nil // data stored in dst.CacheTestNotFoundResponse, return on the first match
		}
	} else {
		dst.CacheTestNotFoundResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) MarshalJSON() ([]byte, error) {
	if src.CacheTestErrorResponse != nil {
		return json.Marshal(&src.CacheTestErrorResponse)
	}

	if src.CacheTestFoundResponse != nil {
		return json.Marshal(&src.CacheTestFoundResponse)
	}

	if src.CacheTestNotFoundResponse != nil {
		return json.Marshal(&src.CacheTestNotFoundResponse)
	}

	return nil, fmt.Errorf("no data in anyOf schemas for ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet")
}

type NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet struct {
	value *ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet
	isSet bool
}

func (v NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) Get() *ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet {
	return v.value
}

func (v *NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) Set(val *ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet(val *ResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) *NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet {
	return &NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet{value: val, isSet: true}
}

func (v NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseTestCacheLookupV1AdminCacheTestDeviceUuidGet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
