/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConsumerResetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerResetResponse{}

// ConsumerResetResponse Consumer reset response model.
type ConsumerResetResponse struct {
	ConsumerName     string `json:"consumer_name"`
	Message          string `json:"message"`
	RemainingPending *int32 `json:"remaining_pending,omitempty"`
	ResetSeq         *int32 `json:"reset_seq,omitempty"`
	Skipped          *int32 `json:"skipped,omitempty"`
	Status           string `json:"status"`
	Stream           string `json:"stream"`
}

type _ConsumerResetResponse ConsumerResetResponse

// NewConsumerResetResponse instantiates a new ConsumerResetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerResetResponse(consumerName string, message string, status string, stream string) *ConsumerResetResponse {
	this := ConsumerResetResponse{}
	this.ConsumerName = consumerName
	this.Message = message
	var remainingPending int32 = 0
	this.RemainingPending = &remainingPending
	var resetSeq int32 = 0
	this.ResetSeq = &resetSeq
	var skipped int32 = 0
	this.Skipped = &skipped
	this.Status = status
	this.Stream = stream
	return &this
}

// NewConsumerResetResponseWithDefaults instantiates a new ConsumerResetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerResetResponseWithDefaults() *ConsumerResetResponse {
	this := ConsumerResetResponse{}
	var remainingPending int32 = 0
	this.RemainingPending = &remainingPending
	var resetSeq int32 = 0
	this.ResetSeq = &resetSeq
	var skipped int32 = 0
	this.Skipped = &skipped
	return &this
}

// GetConsumerName returns the ConsumerName field value
func (o *ConsumerResetResponse) GetConsumerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsumerName
}

// GetConsumerNameOk returns a tuple with the ConsumerName field value
// and a boolean to check if the value has been set.
func (o *ConsumerResetResponse) GetConsumerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerName, true
}

// SetConsumerName sets field value
func (o *ConsumerResetResponse) SetConsumerName(v string) {
	o.ConsumerName = v
}

// GetMessage returns the Message field value
func (o *ConsumerResetResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ConsumerResetResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ConsumerResetResponse) SetMessage(v string) {
	o.Message = v
}

// GetRemainingPending returns the RemainingPending field value if set, zero value otherwise.
func (o *ConsumerResetResponse) GetRemainingPending() int32 {
	if o == nil || IsNil(o.RemainingPending) {
		var ret int32
		return ret
	}
	return *o.RemainingPending
}

// GetRemainingPendingOk returns a tuple with the RemainingPending field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ConsumerResetResponse) GetRemainingPendingOk() (*int32, bool) {
	if o == nil || IsNil(o.RemainingPending) {
		return nil, false
	}
	return o.RemainingPending, true
}

// HasRemainingPending returns a boolean if a field has been set.
func (o *ConsumerResetResponse) HasRemainingPending() bool {
	if o != nil && !IsNil(o.RemainingPending) {
		return true
	}

	return false
}

// SetRemainingPending gets a reference to the given int32 and assigns it to the RemainingPending field.
func (o *ConsumerResetResponse) SetRemainingPending(v int32) {
	o.RemainingPending = &v
}

// GetResetSeq returns the ResetSeq field value if set, zero value otherwise.
func (o *ConsumerResetResponse) GetResetSeq() int32 {
	if o == nil || IsNil(o.ResetSeq) {
		var ret int32
		return ret
	}
	return *o.ResetSeq
}

// GetResetSeqOk returns a tuple with the ResetSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ConsumerResetResponse) GetResetSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.ResetSeq) {
		return nil, false
	}
	return o.ResetSeq, true
}

// HasResetSeq returns a boolean if a field has been set.
func (o *ConsumerResetResponse) HasResetSeq() bool {
	if o != nil && !IsNil(o.ResetSeq) {
		return true
	}

	return false
}

// SetResetSeq gets a reference to the given int32 and assigns it to the ResetSeq field.
func (o *ConsumerResetResponse) SetResetSeq(v int32) {
	o.ResetSeq = &v
}

// GetSkipped returns the Skipped field value if set, zero value otherwise.
func (o *ConsumerResetResponse) GetSkipped() int32 {
	if o == nil || IsNil(o.Skipped) {
		var ret int32
		return ret
	}
	return *o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ConsumerResetResponse) GetSkippedOk() (*int32, bool) {
	if o == nil || IsNil(o.Skipped) {
		return nil, false
	}
	return o.Skipped, true
}

// HasSkipped returns a boolean if a field has been set.
func (o *ConsumerResetResponse) HasSkipped() bool {
	if o != nil && !IsNil(o.Skipped) {
		return true
	}

	return false
}

// SetSkipped gets a reference to the given int32 and assigns it to the Skipped field.
func (o *ConsumerResetResponse) SetSkipped(v int32) {
	o.Skipped = &v
}

// GetStatus returns the Status field value
func (o *ConsumerResetResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConsumerResetResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConsumerResetResponse) SetStatus(v string) {
	o.Status = v
}

// GetStream returns the Stream field value
func (o *ConsumerResetResponse) GetStream() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stream
}

// GetStreamOk returns a tuple with the Stream field value
// and a boolean to check if the value has been set.
func (o *ConsumerResetResponse) GetStreamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stream, true
}

// SetStream sets field value
func (o *ConsumerResetResponse) SetStream(v string) {
	o.Stream = v
}

func (o ConsumerResetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerResetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consumer_name"] = o.ConsumerName
	toSerialize["message"] = o.Message
	if !IsNil(o.RemainingPending) {
		toSerialize["remaining_pending"] = o.RemainingPending
	}
	if !IsNil(o.ResetSeq) {
		toSerialize["reset_seq"] = o.ResetSeq
	}
	if !IsNil(o.Skipped) {
		toSerialize["skipped"] = o.Skipped
	}
	toSerialize["status"] = o.Status
	toSerialize["stream"] = o.Stream
	return toSerialize, nil
}

func (o *ConsumerResetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"consumer_name": false,
		"message":       false,
		"status":        false,
		"stream":        false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerResetResponse := _ConsumerResetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerResetResponse)

	if err != nil {
		return err
	}

	*o = ConsumerResetResponse(varConsumerResetResponse)

	return err
}

type NullableConsumerResetResponse struct {
	value *ConsumerResetResponse
	isSet bool
}

func (v NullableConsumerResetResponse) Get() *ConsumerResetResponse {
	return v.value
}

func (v *NullableConsumerResetResponse) Set(val *ConsumerResetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerResetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerResetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerResetResponse(val *ConsumerResetResponse) *NullableConsumerResetResponse {
	return &NullableConsumerResetResponse{value: val, isSet: true}
}

func (v NullableConsumerResetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerResetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
