query auto_dhcp_subnets_reserved_ips($limit: Int!, $offset: Int!) {
  reserved_ips: ip_addresses(tags: ["dhcp-reserve"], limit: $limit, offset: $offset) {
    address
    ip_version
    parent {
      id
    }
    interfaces {
      name
      mac_address
      role {
        name
      }
      device {
        id
        name
        serial
        platform {
          name
        }
        status {
          name
        }
        configmanagerdevicestatus {
          ztp_enabled
          is_aggregate_managed
        }
      }
    }
  }
}
