enabled: true
auto_sync_draft: false
auto_sync_ready: true
trustees_override:
  - dmathur0
  - jojung1
  - kiwueke2
  - polarweasel
  - ross-bryan
  - ryanheffernan
  - spidercensus
  - susanhooks
  - zsblevins
vetters_override:
  - dmathur0
  - jojung1
  - kiwueke2
  - polarweasel
  - ross-bryan
  - ryanheffernan
  - spidercensus
  - susanhooks
  - zsblevins
