/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DiffGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffGroup{}

// DiffGroup A group of devices with identical diffs.  Note: Each device has its own intended config file and commit SHA. Grouping is only based on identical diff content, not commit IDs.
type DiffGroup struct {
	Devices     []DeviceDiffData `json:"devices"`
	DiffContent string           `json:"diff_content"`
	DiffHash    string           `json:"diff_hash"`
}

type _DiffGroup DiffGroup

// NewDiffGroup instantiates a new DiffGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffGroup(devices []DeviceDiffData, diffContent string, diffHash string) *DiffGroup {
	this := DiffGroup{}
	this.Devices = devices
	this.DiffContent = diffContent
	this.DiffHash = diffHash
	return &this
}

// NewDiffGroupWithDefaults instantiates a new DiffGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffGroupWithDefaults() *DiffGroup {
	this := DiffGroup{}
	return &this
}

// GetDevices returns the Devices field value
func (o *DiffGroup) GetDevices() []DeviceDiffData {
	if o == nil {
		var ret []DeviceDiffData
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *DiffGroup) GetDevicesOk() ([]DeviceDiffData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *DiffGroup) SetDevices(v []DeviceDiffData) {
	o.Devices = v
}

// GetDiffContent returns the DiffContent field value
func (o *DiffGroup) GetDiffContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiffContent
}

// GetDiffContentOk returns a tuple with the DiffContent field value
// and a boolean to check if the value has been set.
func (o *DiffGroup) GetDiffContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiffContent, true
}

// SetDiffContent sets field value
func (o *DiffGroup) SetDiffContent(v string) {
	o.DiffContent = v
}

// GetDiffHash returns the DiffHash field value
func (o *DiffGroup) GetDiffHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiffHash
}

// GetDiffHashOk returns a tuple with the DiffHash field value
// and a boolean to check if the value has been set.
func (o *DiffGroup) GetDiffHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiffHash, true
}

// SetDiffHash sets field value
func (o *DiffGroup) SetDiffHash(v string) {
	o.DiffHash = v
}

func (o DiffGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devices"] = o.Devices
	toSerialize["diff_content"] = o.DiffContent
	toSerialize["diff_hash"] = o.DiffHash
	return toSerialize, nil
}

func (o *DiffGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"devices",
		"diff_content",
		"diff_hash",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiffGroup := _DiffGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiffGroup)

	if err != nil {
		return err
	}

	*o = DiffGroup(varDiffGroup)

	return err
}

type NullableDiffGroup struct {
	value *DiffGroup
	isSet bool
}

func (v NullableDiffGroup) Get() *DiffGroup {
	return v.value
}

func (v *NullableDiffGroup) Set(val *DiffGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffGroup(val *DiffGroup) *NullableDiffGroup {
	return &NullableDiffGroup{value: val, isSet: true}
}

func (v NullableDiffGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
