/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TriggerEnum Enum of potential backup triggers.
type TriggerEnum string

// List of TriggerEnum
const (
	SCHEDULED TriggerEnum = "SCHEDULED"
	SYSLOG    TriggerEnum = "SYSLOG"
	WORKFLOW  TriggerEnum = "WORKFLOW"
	API       TriggerEnum = "API"
)

// All allowed values of TriggerEnum enum
var AllowedTriggerEnumEnumValues = []TriggerEnum{
	"SCHEDULED",
	"SYSLOG",
	"WORKFLOW",
	"API",
}

func (v *TriggerEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TriggerEnum(value)
	for _, existing := range AllowedTriggerEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TriggerEnum", value)
}

// NewTriggerEnumFromValue returns a pointer to a valid TriggerEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTriggerEnumFromValue(v string) (*TriggerEnum, error) {
	ev := TriggerEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TriggerEnum: valid values are %v", v, AllowedTriggerEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TriggerEnum) IsValid() bool {
	for _, existing := range AllowedTriggerEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TriggerEnum value
func (v TriggerEnum) Ptr() *TriggerEnum {
	return &v
}

type NullableTriggerEnum struct {
	value *TriggerEnum
	isSet bool
}

func (v NullableTriggerEnum) Get() *TriggerEnum {
	return v.value
}

func (v *NullableTriggerEnum) Set(val *TriggerEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerEnum(val *TriggerEnum) *NullableTriggerEnum {
	return &NullableTriggerEnum{value: val, isSet: true}
}

func (v NullableTriggerEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
