/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpXOverlayDeletionInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpXOverlayDeletionInput{}

// SpXOverlayDeletionInput SpX Overlay Deletion Workflow Input Definition.
type SpXOverlayDeletionInput struct {
	NamespaceTag *string `json:"namespace_tag,omitempty"`
	// Identifier of the SpX overlay to delete.
	OverlayId string `json:"overlay_id"`
	Site      string `json:"site"`
}

type _SpXOverlayDeletionInput SpXOverlayDeletionInput

// NewSpXOverlayDeletionInput instantiates a new SpXOverlayDeletionInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpXOverlayDeletionInput(overlayId string, site string) *SpXOverlayDeletionInput {
	this := SpXOverlayDeletionInput{}
	var namespaceTag string = "spectrumx"
	this.NamespaceTag = &namespaceTag
	this.OverlayId = overlayId
	this.Site = site
	return &this
}

// NewSpXOverlayDeletionInputWithDefaults instantiates a new SpXOverlayDeletionInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpXOverlayDeletionInputWithDefaults() *SpXOverlayDeletionInput {
	this := SpXOverlayDeletionInput{}
	var namespaceTag string = "spectrumx"
	this.NamespaceTag = &namespaceTag
	return &this
}

// GetNamespaceTag returns the NamespaceTag field value if set, zero value otherwise.
func (o *SpXOverlayDeletionInput) GetNamespaceTag() string {
	if o == nil || IsNil(o.NamespaceTag) {
		var ret string
		return ret
	}
	return *o.NamespaceTag
}

// GetNamespaceTagOk returns a tuple with the NamespaceTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpXOverlayDeletionInput) GetNamespaceTagOk() (*string, bool) {
	if o == nil || IsNil(o.NamespaceTag) {
		return nil, false
	}
	return o.NamespaceTag, true
}

// HasNamespaceTag returns a boolean if a field has been set.
func (o *SpXOverlayDeletionInput) HasNamespaceTag() bool {
	if o != nil && !IsNil(o.NamespaceTag) {
		return true
	}

	return false
}

// SetNamespaceTag gets a reference to the given string and assigns it to the NamespaceTag field.
func (o *SpXOverlayDeletionInput) SetNamespaceTag(v string) {
	o.NamespaceTag = &v
}

// GetOverlayId returns the OverlayId field value
func (o *SpXOverlayDeletionInput) GetOverlayId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OverlayId
}

// GetOverlayIdOk returns a tuple with the OverlayId field value
// and a boolean to check if the value has been set.
func (o *SpXOverlayDeletionInput) GetOverlayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverlayId, true
}

// SetOverlayId sets field value
func (o *SpXOverlayDeletionInput) SetOverlayId(v string) {
	o.OverlayId = v
}

// GetSite returns the Site field value
func (o *SpXOverlayDeletionInput) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *SpXOverlayDeletionInput) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *SpXOverlayDeletionInput) SetSite(v string) {
	o.Site = v
}

func (o SpXOverlayDeletionInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpXOverlayDeletionInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NamespaceTag) {
		toSerialize["namespace_tag"] = o.NamespaceTag
	}
	toSerialize["overlay_id"] = o.OverlayId
	toSerialize["site"] = o.Site
	return toSerialize, nil
}

func (o *SpXOverlayDeletionInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"overlay_id",
		"site",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpXOverlayDeletionInput := _SpXOverlayDeletionInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpXOverlayDeletionInput)

	if err != nil {
		return err
	}

	*o = SpXOverlayDeletionInput(varSpXOverlayDeletionInput)

	return err
}

type NullableSpXOverlayDeletionInput struct {
	value *SpXOverlayDeletionInput
	isSet bool
}

func (v NullableSpXOverlayDeletionInput) Get() *SpXOverlayDeletionInput {
	return v.value
}

func (v *NullableSpXOverlayDeletionInput) Set(val *SpXOverlayDeletionInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSpXOverlayDeletionInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSpXOverlayDeletionInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpXOverlayDeletionInput(val *SpXOverlayDeletionInput) *NullableSpXOverlayDeletionInput {
	return &NullableSpXOverlayDeletionInput{value: val, isSet: true}
}

func (v NullableSpXOverlayDeletionInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpXOverlayDeletionInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
