/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeviceDiffData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceDiffData{}

// DeviceDiffData Data structure for device diff information.
type DeviceDiffData struct {
	CommitId       NullableString    `json:"commit_id,omitempty"`
	Device         NetworkDeviceData `json:"device"`
	Diff           NullableString    `json:"diff,omitempty"`
	Error          NullableString    `json:"error,omitempty"`
	IntendedConfig NullableString    `json:"intended_config,omitempty"`
}

type _DeviceDiffData DeviceDiffData

// NewDeviceDiffData instantiates a new DeviceDiffData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceDiffData(device NetworkDeviceData) *DeviceDiffData {
	this := DeviceDiffData{}
	this.Device = device
	return &this
}

// NewDeviceDiffDataWithDefaults instantiates a new DeviceDiffData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceDiffDataWithDefaults() *DeviceDiffData {
	this := DeviceDiffData{}
	return &this
}

// GetCommitId returns the CommitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceDiffData) GetCommitId() string {
	if o == nil || IsNil(o.CommitId.Get()) {
		var ret string
		return ret
	}
	return *o.CommitId.Get()
}

// GetCommitIdOk returns a tuple with the CommitId field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceDiffData) GetCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommitId.Get(), o.CommitId.IsSet()
}

// HasCommitId returns a boolean if a field has been set.
func (o *DeviceDiffData) HasCommitId() bool {
	if o != nil && o.CommitId.IsSet() {
		return true
	}

	return false
}

// SetCommitId gets a reference to the given NullableString and assigns it to the CommitId field.
func (o *DeviceDiffData) SetCommitId(v string) {
	o.CommitId.Set(&v)
}

// SetCommitIdNil sets the value for CommitId to be an explicit nil
func (o *DeviceDiffData) SetCommitIdNil() {
	o.CommitId.Set(nil)
}

// UnsetCommitId ensures that no value is present for CommitId, not even an explicit nil
func (o *DeviceDiffData) UnsetCommitId() {
	o.CommitId.Unset()
}

// GetDevice returns the Device field value
func (o *DeviceDiffData) GetDevice() NetworkDeviceData {
	if o == nil {
		var ret NetworkDeviceData
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *DeviceDiffData) GetDeviceOk() (*NetworkDeviceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *DeviceDiffData) SetDevice(v NetworkDeviceData) {
	o.Device = v
}

// GetDiff returns the Diff field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceDiffData) GetDiff() string {
	if o == nil || IsNil(o.Diff.Get()) {
		var ret string
		return ret
	}
	return *o.Diff.Get()
}

// GetDiffOk returns a tuple with the Diff field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceDiffData) GetDiffOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Diff.Get(), o.Diff.IsSet()
}

// HasDiff returns a boolean if a field has been set.
func (o *DeviceDiffData) HasDiff() bool {
	if o != nil && o.Diff.IsSet() {
		return true
	}

	return false
}

// SetDiff gets a reference to the given NullableString and assigns it to the Diff field.
func (o *DeviceDiffData) SetDiff(v string) {
	o.Diff.Set(&v)
}

// SetDiffNil sets the value for Diff to be an explicit nil
func (o *DeviceDiffData) SetDiffNil() {
	o.Diff.Set(nil)
}

// UnsetDiff ensures that no value is present for Diff, not even an explicit nil
func (o *DeviceDiffData) UnsetDiff() {
	o.Diff.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceDiffData) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceDiffData) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *DeviceDiffData) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *DeviceDiffData) SetError(v string) {
	o.Error.Set(&v)
}

// SetErrorNil sets the value for Error to be an explicit nil
func (o *DeviceDiffData) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *DeviceDiffData) UnsetError() {
	o.Error.Unset()
}

// GetIntendedConfig returns the IntendedConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceDiffData) GetIntendedConfig() string {
	if o == nil || IsNil(o.IntendedConfig.Get()) {
		var ret string
		return ret
	}
	return *o.IntendedConfig.Get()
}

// GetIntendedConfigOk returns a tuple with the IntendedConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceDiffData) GetIntendedConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntendedConfig.Get(), o.IntendedConfig.IsSet()
}

// HasIntendedConfig returns a boolean if a field has been set.
func (o *DeviceDiffData) HasIntendedConfig() bool {
	if o != nil && o.IntendedConfig.IsSet() {
		return true
	}

	return false
}

// SetIntendedConfig gets a reference to the given NullableString and assigns it to the IntendedConfig field.
func (o *DeviceDiffData) SetIntendedConfig(v string) {
	o.IntendedConfig.Set(&v)
}

// SetIntendedConfigNil sets the value for IntendedConfig to be an explicit nil
func (o *DeviceDiffData) SetIntendedConfigNil() {
	o.IntendedConfig.Set(nil)
}

// UnsetIntendedConfig ensures that no value is present for IntendedConfig, not even an explicit nil
func (o *DeviceDiffData) UnsetIntendedConfig() {
	o.IntendedConfig.Unset()
}

func (o DeviceDiffData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceDiffData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CommitId.IsSet() {
		toSerialize["commit_id"] = o.CommitId.Get()
	}
	toSerialize["device"] = o.Device
	if o.Diff.IsSet() {
		toSerialize["diff"] = o.Diff.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.IntendedConfig.IsSet() {
		toSerialize["intended_config"] = o.IntendedConfig.Get()
	}
	return toSerialize, nil
}

func (o *DeviceDiffData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceDiffData := _DeviceDiffData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceDiffData)

	if err != nil {
		return err
	}

	*o = DeviceDiffData(varDeviceDiffData)

	return err
}

type NullableDeviceDiffData struct {
	value *DeviceDiffData
	isSet bool
}

func (v NullableDeviceDiffData) Get() *DeviceDiffData {
	return v.value
}

func (v *NullableDeviceDiffData) Set(val *DeviceDiffData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceDiffData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceDiffData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceDiffData(val *DeviceDiffData) *NullableDeviceDiffData {
	return &NullableDeviceDiffData{value: val, isSet: true}
}

func (v NullableDeviceDiffData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceDiffData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
