/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BackupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupInput{}

// BackupInput Backup Workflow Input Definiton.
type BackupInput struct {
	DeviceId               string         `json:"device_id"`
	IntendedConfigCommitId NullableString `json:"intended_config_commit_id"`
	Trigger                TriggerEnum    `json:"trigger"`
	User                   NullableString `json:"user"`
	UserDomain             NullableString `json:"user_domain"`
	WorkflowId             NullableString `json:"workflow_id"`
}

type _BackupInput BackupInput

// NewBackupInput instantiates a new BackupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupInput(deviceId string, intendedConfigCommitId NullableString, trigger TriggerEnum, user NullableString, userDomain NullableString, workflowId NullableString) *BackupInput {
	this := BackupInput{}
	this.DeviceId = deviceId
	this.IntendedConfigCommitId = intendedConfigCommitId
	this.Trigger = trigger
	this.User = user
	this.UserDomain = userDomain
	this.WorkflowId = workflowId
	return &this
}

// NewBackupInputWithDefaults instantiates a new BackupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupInputWithDefaults() *BackupInput {
	this := BackupInput{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *BackupInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *BackupInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *BackupInput) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetIntendedConfigCommitId returns the IntendedConfigCommitId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BackupInput) GetIntendedConfigCommitId() string {
	if o == nil || o.IntendedConfigCommitId.Get() == nil {
		var ret string
		return ret
	}

	return *o.IntendedConfigCommitId.Get()
}

// GetIntendedConfigCommitIdOk returns a tuple with the IntendedConfigCommitId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupInput) GetIntendedConfigCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntendedConfigCommitId.Get(), o.IntendedConfigCommitId.IsSet()
}

// SetIntendedConfigCommitId sets field value
func (o *BackupInput) SetIntendedConfigCommitId(v string) {
	o.IntendedConfigCommitId.Set(&v)
}

// GetTrigger returns the Trigger field value
func (o *BackupInput) GetTrigger() TriggerEnum {
	if o == nil {
		var ret TriggerEnum
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *BackupInput) GetTriggerOk() (*TriggerEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *BackupInput) SetTrigger(v TriggerEnum) {
	o.Trigger = v
}

// GetUser returns the User field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BackupInput) GetUser() string {
	if o == nil || o.User.Get() == nil {
		var ret string
		return ret
	}

	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupInput) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// SetUser sets field value
func (o *BackupInput) SetUser(v string) {
	o.User.Set(&v)
}

// GetUserDomain returns the UserDomain field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BackupInput) GetUserDomain() string {
	if o == nil || o.UserDomain.Get() == nil {
		var ret string
		return ret
	}

	return *o.UserDomain.Get()
}

// GetUserDomainOk returns a tuple with the UserDomain field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupInput) GetUserDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserDomain.Get(), o.UserDomain.IsSet()
}

// SetUserDomain sets field value
func (o *BackupInput) SetUserDomain(v string) {
	o.UserDomain.Set(&v)
}

// GetWorkflowId returns the WorkflowId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BackupInput) GetWorkflowId() string {
	if o == nil || o.WorkflowId.Get() == nil {
		var ret string
		return ret
	}

	return *o.WorkflowId.Get()
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupInput) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowId.Get(), o.WorkflowId.IsSet()
}

// SetWorkflowId sets field value
func (o *BackupInput) SetWorkflowId(v string) {
	o.WorkflowId.Set(&v)
}

func (o BackupInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	toSerialize["intended_config_commit_id"] = o.IntendedConfigCommitId.Get()
	toSerialize["trigger"] = o.Trigger
	toSerialize["user"] = o.User.Get()
	toSerialize["user_domain"] = o.UserDomain.Get()
	toSerialize["workflow_id"] = o.WorkflowId.Get()
	return toSerialize, nil
}

func (o *BackupInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"device_id",
		"intended_config_commit_id",
		"trigger",
		"user",
		"user_domain",
		"workflow_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupInput := _BackupInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupInput)

	if err != nil {
		return err
	}

	*o = BackupInput(varBackupInput)

	return err
}

type NullableBackupInput struct {
	value *BackupInput
	isSet bool
}

func (v NullableBackupInput) Get() *BackupInput {
	return v.value
}

func (v *NullableBackupInput) Set(val *BackupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupInput(val *BackupInput) *NullableBackupInput {
	return &NullableBackupInput{value: val, isSet: true}
}

func (v NullableBackupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
