/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchDeployInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchDeployInput{}

// BatchDeployInput Input for batch deploy child workflow.
type BatchDeployInput struct {
	BatchDevices     []DeviceDiffData `json:"batch_devices"`
	BatchNumber      NullableInt32    `json:"batch_number,omitempty"`
	CommitConfirm    *bool            `json:"commit_confirm,omitempty"`
	DiffGroup        DiffGroup        `json:"diff_group"`
	ParentWorkflowId string           `json:"parent_workflow_id"`
}

type _BatchDeployInput BatchDeployInput

// NewBatchDeployInput instantiates a new BatchDeployInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchDeployInput(batchDevices []DeviceDiffData, diffGroup DiffGroup, parentWorkflowId string) *BatchDeployInput {
	this := BatchDeployInput{}
	this.BatchDevices = batchDevices
	var commitConfirm bool = true
	this.CommitConfirm = &commitConfirm
	this.DiffGroup = diffGroup
	this.ParentWorkflowId = parentWorkflowId
	return &this
}

// NewBatchDeployInputWithDefaults instantiates a new BatchDeployInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchDeployInputWithDefaults() *BatchDeployInput {
	this := BatchDeployInput{}
	var commitConfirm bool = true
	this.CommitConfirm = &commitConfirm
	return &this
}

// GetBatchDevices returns the BatchDevices field value
func (o *BatchDeployInput) GetBatchDevices() []DeviceDiffData {
	if o == nil {
		var ret []DeviceDiffData
		return ret
	}

	return o.BatchDevices
}

// GetBatchDevicesOk returns a tuple with the BatchDevices field value
// and a boolean to check if the value has been set.
func (o *BatchDeployInput) GetBatchDevicesOk() ([]DeviceDiffData, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatchDevices, true
}

// SetBatchDevices sets field value
func (o *BatchDeployInput) SetBatchDevices(v []DeviceDiffData) {
	o.BatchDevices = v
}

// GetBatchNumber returns the BatchNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchDeployInput) GetBatchNumber() int32 {
	if o == nil || IsNil(o.BatchNumber.Get()) {
		var ret int32
		return ret
	}
	return *o.BatchNumber.Get()
}

// GetBatchNumberOk returns a tuple with the BatchNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BatchDeployInput) GetBatchNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BatchNumber.Get(), o.BatchNumber.IsSet()
}

// HasBatchNumber returns a boolean if a field has been set.
func (o *BatchDeployInput) HasBatchNumber() bool {
	if o != nil && o.BatchNumber.IsSet() {
		return true
	}

	return false
}

// SetBatchNumber gets a reference to the given NullableInt32 and assigns it to the BatchNumber field.
func (o *BatchDeployInput) SetBatchNumber(v int32) {
	o.BatchNumber.Set(&v)
}

// SetBatchNumberNil sets the value for BatchNumber to be an explicit nil
func (o *BatchDeployInput) SetBatchNumberNil() {
	o.BatchNumber.Set(nil)
}

// UnsetBatchNumber ensures that no value is present for BatchNumber, not even an explicit nil
func (o *BatchDeployInput) UnsetBatchNumber() {
	o.BatchNumber.Unset()
}

// GetCommitConfirm returns the CommitConfirm field value if set, zero value otherwise.
func (o *BatchDeployInput) GetCommitConfirm() bool {
	if o == nil || IsNil(o.CommitConfirm) {
		var ret bool
		return ret
	}
	return *o.CommitConfirm
}

// GetCommitConfirmOk returns a tuple with the CommitConfirm field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *BatchDeployInput) GetCommitConfirmOk() (*bool, bool) {
	if o == nil || IsNil(o.CommitConfirm) {
		return nil, false
	}
	return o.CommitConfirm, true
}

// HasCommitConfirm returns a boolean if a field has been set.
func (o *BatchDeployInput) HasCommitConfirm() bool {
	if o != nil && !IsNil(o.CommitConfirm) {
		return true
	}

	return false
}

// SetCommitConfirm gets a reference to the given bool and assigns it to the CommitConfirm field.
func (o *BatchDeployInput) SetCommitConfirm(v bool) {
	o.CommitConfirm = &v
}

// GetDiffGroup returns the DiffGroup field value
func (o *BatchDeployInput) GetDiffGroup() DiffGroup {
	if o == nil {
		var ret DiffGroup
		return ret
	}

	return o.DiffGroup
}

// GetDiffGroupOk returns a tuple with the DiffGroup field value
// and a boolean to check if the value has been set.
func (o *BatchDeployInput) GetDiffGroupOk() (*DiffGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiffGroup, true
}

// SetDiffGroup sets field value
func (o *BatchDeployInput) SetDiffGroup(v DiffGroup) {
	o.DiffGroup = v
}

// GetParentWorkflowId returns the ParentWorkflowId field value
func (o *BatchDeployInput) GetParentWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentWorkflowId
}

// GetParentWorkflowIdOk returns a tuple with the ParentWorkflowId field value
// and a boolean to check if the value has been set.
func (o *BatchDeployInput) GetParentWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentWorkflowId, true
}

// SetParentWorkflowId sets field value
func (o *BatchDeployInput) SetParentWorkflowId(v string) {
	o.ParentWorkflowId = v
}

func (o BatchDeployInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchDeployInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["batch_devices"] = o.BatchDevices
	if o.BatchNumber.IsSet() {
		toSerialize["batch_number"] = o.BatchNumber.Get()
	}
	if !IsNil(o.CommitConfirm) {
		toSerialize["commit_confirm"] = o.CommitConfirm
	}
	toSerialize["diff_group"] = o.DiffGroup
	toSerialize["parent_workflow_id"] = o.ParentWorkflowId
	return toSerialize, nil
}

func (o *BatchDeployInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"batch_devices":      false,
		"diff_group":         false,
		"parent_workflow_id": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchDeployInput := _BatchDeployInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchDeployInput)

	if err != nil {
		return err
	}

	*o = BatchDeployInput(varBatchDeployInput)

	return err
}

type NullableBatchDeployInput struct {
	value *BatchDeployInput
	isSet bool
}

func (v NullableBatchDeployInput) Get() *BatchDeployInput {
	return v.value
}

func (v *NullableBatchDeployInput) Set(val *BatchDeployInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchDeployInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchDeployInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchDeployInput(val *BatchDeployInput) *NullableBatchDeployInput {
	return &NullableBatchDeployInput{value: val, isSet: true}
}

func (v NullableBatchDeployInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchDeployInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
