/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TenantDeployInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantDeployInput{}

// TenantDeployInput struct for TenantDeployInput
type TenantDeployInput struct {
	// Optional config-store commit ID for the intended startup configuration from the same render snapshot as tenant_config_commit_id. Must be supplied with tenant_config_commit_id; omit both to deploy the latest tenant and intended configurations.
	IntendedConfigCommitId string `json:"intended_config_commit_id" validate:"regexp=^\\\\d+$"`
	// Optional config-store commit ID for the tenant configuration. Must be supplied with intended_config_commit_id; omit both to deploy the latest tenant and intended configurations.
	TenantConfigCommitId string `json:"tenant_config_commit_id" validate:"regexp=^\\\\d+$"`
}

type _TenantDeployInput TenantDeployInput

// NewTenantDeployInput instantiates a new TenantDeployInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantDeployInput(intendedConfigCommitId string, tenantConfigCommitId string) *TenantDeployInput {
	this := TenantDeployInput{}
	this.IntendedConfigCommitId = intendedConfigCommitId
	this.TenantConfigCommitId = tenantConfigCommitId
	return &this
}

// NewTenantDeployInputWithDefaults instantiates a new TenantDeployInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantDeployInputWithDefaults() *TenantDeployInput {
	this := TenantDeployInput{}
	return &this
}

// GetIntendedConfigCommitId returns the IntendedConfigCommitId field value
func (o *TenantDeployInput) GetIntendedConfigCommitId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntendedConfigCommitId
}

// GetIntendedConfigCommitIdOk returns a tuple with the IntendedConfigCommitId field value
// and a boolean to check if the value has been set.
func (o *TenantDeployInput) GetIntendedConfigCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntendedConfigCommitId, true
}

// SetIntendedConfigCommitId sets field value
func (o *TenantDeployInput) SetIntendedConfigCommitId(v string) {
	o.IntendedConfigCommitId = v
}

// GetTenantConfigCommitId returns the TenantConfigCommitId field value
func (o *TenantDeployInput) GetTenantConfigCommitId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantConfigCommitId
}

// GetTenantConfigCommitIdOk returns a tuple with the TenantConfigCommitId field value
// and a boolean to check if the value has been set.
func (o *TenantDeployInput) GetTenantConfigCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantConfigCommitId, true
}

// SetTenantConfigCommitId sets field value
func (o *TenantDeployInput) SetTenantConfigCommitId(v string) {
	o.TenantConfigCommitId = v
}

func (o TenantDeployInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantDeployInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["intended_config_commit_id"] = o.IntendedConfigCommitId
	toSerialize["tenant_config_commit_id"] = o.TenantConfigCommitId
	return toSerialize, nil
}

func (o *TenantDeployInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"intended_config_commit_id",
		"tenant_config_commit_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantDeployInput := _TenantDeployInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantDeployInput)

	if err != nil {
		return err
	}

	*o = TenantDeployInput(varTenantDeployInput)

	return err
}

type NullableTenantDeployInput struct {
	value *TenantDeployInput
	isSet bool
}

func (v NullableTenantDeployInput) Get() *TenantDeployInput {
	return v.value
}

func (v *NullableTenantDeployInput) Set(val *TenantDeployInput) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantDeployInput) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantDeployInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantDeployInput(val *TenantDeployInput) *NullableTenantDeployInput {
	return &NullableTenantDeployInput{value: val, isSet: true}
}

func (v NullableTenantDeployInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantDeployInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
