/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// SearchAttributesValue struct for SearchAttributesValue
type SearchAttributesValue struct {
	ArrayOfBool     *[]bool
	ArrayOfFloat32  *[]float32
	ArrayOfInt32    *[]int32
	ArrayOfString   *[]string
	ArrayOfTimeTime *[]time.Time
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SearchAttributesValue) UnmarshalJSON(data []byte) error {
	var err error
	*dst = SearchAttributesValue{}
	var value interface{}
	if err = json.Unmarshal(data, &value); err != nil {
		return err
	}
	if value == nil {
		return fmt.Errorf("null is not valid for SearchAttributesValue")
	}
	// try to unmarshal JSON data into ArrayOfBool
	err = json.Unmarshal(data, &dst.ArrayOfBool)
	if err == nil {
		jsonArrayOfBool, _ := json.Marshal(dst.ArrayOfBool)
		if string(jsonArrayOfBool) == "{}" { // empty struct
			dst.ArrayOfBool = nil
		} else {
			return nil // data stored in dst.ArrayOfBool, return on the first match
		}
	} else {
		dst.ArrayOfBool = nil
	}

	// try to unmarshal JSON data into ArrayOfFloat32
	err = json.Unmarshal(data, &dst.ArrayOfFloat32)
	if err == nil {
		jsonArrayOfFloat32, _ := json.Marshal(dst.ArrayOfFloat32)
		if string(jsonArrayOfFloat32) == "{}" { // empty struct
			dst.ArrayOfFloat32 = nil
		} else {
			return nil // data stored in dst.ArrayOfFloat32, return on the first match
		}
	} else {
		dst.ArrayOfFloat32 = nil
	}

	// try to unmarshal JSON data into ArrayOfInt32
	err = json.Unmarshal(data, &dst.ArrayOfInt32)
	if err == nil {
		jsonArrayOfInt32, _ := json.Marshal(dst.ArrayOfInt32)
		if string(jsonArrayOfInt32) == "{}" { // empty struct
			dst.ArrayOfInt32 = nil
		} else {
			return nil // data stored in dst.ArrayOfInt32, return on the first match
		}
	} else {
		dst.ArrayOfInt32 = nil
	}

	// try to unmarshal JSON data into ArrayOfString
	err = json.Unmarshal(data, &dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			return nil // data stored in dst.ArrayOfString, return on the first match
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal JSON data into ArrayOfTimeTime
	err = json.Unmarshal(data, &dst.ArrayOfTimeTime)
	if err == nil {
		jsonArrayOfTimeTime, _ := json.Marshal(dst.ArrayOfTimeTime)
		if string(jsonArrayOfTimeTime) == "{}" { // empty struct
			dst.ArrayOfTimeTime = nil
		} else {
			return nil // data stored in dst.ArrayOfTimeTime, return on the first match
		}
	} else {
		dst.ArrayOfTimeTime = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SearchAttributesValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SearchAttributesValue) MarshalJSON() ([]byte, error) {
	if src.ArrayOfBool != nil {
		return json.Marshal(&src.ArrayOfBool)
	}

	if src.ArrayOfFloat32 != nil {
		return json.Marshal(&src.ArrayOfFloat32)
	}

	if src.ArrayOfInt32 != nil {
		return json.Marshal(&src.ArrayOfInt32)
	}

	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.ArrayOfTimeTime != nil {
		return json.Marshal(&src.ArrayOfTimeTime)
	}

	return nil, fmt.Errorf("no data in anyOf schemas for SearchAttributesValue")
}

type NullableSearchAttributesValue struct {
	value *SearchAttributesValue
	isSet bool
}

func (v NullableSearchAttributesValue) Get() *SearchAttributesValue {
	return v.value
}

func (v *NullableSearchAttributesValue) Set(val *SearchAttributesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchAttributesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchAttributesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchAttributesValue(val *SearchAttributesValue) *NullableSearchAttributesValue {
	return &NullableSearchAttributesValue{value: val, isSet: true}
}

func (v NullableSearchAttributesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchAttributesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
