/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"encoding/json"
	"fmt"
)

// Device1 struct for Device1
type Device1 struct {
	NetworkDeviceData *NetworkDeviceData
	String            *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Device1) UnmarshalJSON(data []byte) error {
	var err error
	*dst = Device1{}
	var value interface{}
	if err = json.Unmarshal(data, &value); err != nil {
		return err
	}
	if value == nil {
		return fmt.Errorf("null is not valid for Device1")
	}
	// try to unmarshal JSON data into NetworkDeviceData
	err = json.Unmarshal(data, &dst.NetworkDeviceData)
	if err == nil {
		jsonNetworkDeviceData, _ := json.Marshal(dst.NetworkDeviceData)
		if string(jsonNetworkDeviceData) == "{}" { // empty struct
			dst.NetworkDeviceData = nil
		} else {
			return nil // data stored in dst.NetworkDeviceData, return on the first match
		}
	} else {
		dst.NetworkDeviceData = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Device1)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Device1) MarshalJSON() ([]byte, error) {
	if src.NetworkDeviceData != nil {
		return json.Marshal(&src.NetworkDeviceData)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, fmt.Errorf("no data in anyOf schemas for Device1")
}

type NullableDevice1 struct {
	value *Device1
	isSet bool
}

func (v NullableDevice1) Get() *Device1 {
	return v.value
}

func (v *NullableDevice1) Set(val *Device1) {
	v.value = val
	v.isSet = true
}

func (v NullableDevice1) IsSet() bool {
	return v.isSet
}

func (v *NullableDevice1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevice1(val *Device1) *NullableDevice1 {
	return &NullableDevice1{value: val, isSet: true}
}

func (v NullableDevice1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevice1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
