/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeviceCableValidationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceCableValidationInput{}

// DeviceCableValidationInput Input for Device Cable Validation Workflow.
type DeviceCableValidationInput struct {
	Device           NullableNetworkDeviceData `json:"device,omitempty"`
	DeviceId         string                    `json:"device_id"`
	IgnoreNoNeighbor *bool                     `json:"ignore_no_neighbor,omitempty"`
}

type _DeviceCableValidationInput DeviceCableValidationInput

// NewDeviceCableValidationInput instantiates a new DeviceCableValidationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceCableValidationInput(deviceId string) *DeviceCableValidationInput {
	this := DeviceCableValidationInput{}
	this.DeviceId = deviceId
	var ignoreNoNeighbor bool = false
	this.IgnoreNoNeighbor = &ignoreNoNeighbor
	return &this
}

// NewDeviceCableValidationInputWithDefaults instantiates a new DeviceCableValidationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceCableValidationInputWithDefaults() *DeviceCableValidationInput {
	this := DeviceCableValidationInput{}
	var ignoreNoNeighbor bool = false
	this.IgnoreNoNeighbor = &ignoreNoNeighbor
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceCableValidationInput) GetDevice() NetworkDeviceData {
	if o == nil || IsNil(o.Device.Get()) {
		var ret NetworkDeviceData
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeviceCableValidationInput) GetDeviceOk() (*NetworkDeviceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *DeviceCableValidationInput) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableNetworkDeviceData and assigns it to the Device field.
func (o *DeviceCableValidationInput) SetDevice(v NetworkDeviceData) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *DeviceCableValidationInput) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *DeviceCableValidationInput) UnsetDevice() {
	o.Device.Unset()
}

// GetDeviceId returns the DeviceId field value
func (o *DeviceCableValidationInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *DeviceCableValidationInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *DeviceCableValidationInput) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetIgnoreNoNeighbor returns the IgnoreNoNeighbor field value if set, zero value otherwise.
func (o *DeviceCableValidationInput) GetIgnoreNoNeighbor() bool {
	if o == nil || IsNil(o.IgnoreNoNeighbor) {
		var ret bool
		return ret
	}
	return *o.IgnoreNoNeighbor
}

// GetIgnoreNoNeighborOk returns a tuple with the IgnoreNoNeighbor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceCableValidationInput) GetIgnoreNoNeighborOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreNoNeighbor) {
		return nil, false
	}
	return o.IgnoreNoNeighbor, true
}

// HasIgnoreNoNeighbor returns a boolean if a field has been set.
func (o *DeviceCableValidationInput) HasIgnoreNoNeighbor() bool {
	if o != nil && !IsNil(o.IgnoreNoNeighbor) {
		return true
	}

	return false
}

// SetIgnoreNoNeighbor gets a reference to the given bool and assigns it to the IgnoreNoNeighbor field.
func (o *DeviceCableValidationInput) SetIgnoreNoNeighbor(v bool) {
	o.IgnoreNoNeighbor = &v
}

func (o DeviceCableValidationInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceCableValidationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	toSerialize["device_id"] = o.DeviceId
	if !IsNil(o.IgnoreNoNeighbor) {
		toSerialize["ignore_no_neighbor"] = o.IgnoreNoNeighbor
	}
	return toSerialize, nil
}

func (o *DeviceCableValidationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"device_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceCableValidationInput := _DeviceCableValidationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceCableValidationInput)

	if err != nil {
		return err
	}

	*o = DeviceCableValidationInput(varDeviceCableValidationInput)

	return err
}

type NullableDeviceCableValidationInput struct {
	value *DeviceCableValidationInput
	isSet bool
}

func (v NullableDeviceCableValidationInput) Get() *DeviceCableValidationInput {
	return v.value
}

func (v *NullableDeviceCableValidationInput) Set(val *DeviceCableValidationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceCableValidationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceCableValidationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceCableValidationInput(val *DeviceCableValidationInput) *NullableDeviceCableValidationInput {
	return &NullableDeviceCableValidationInput{value: val, isSet: true}
}

func (v NullableDeviceCableValidationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceCableValidationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
