/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BackupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupInput{}

// BackupInput Backup Workflow Input Definiton.
type BackupInput struct {
	// Identifier of the network device to back up.
	DeviceId string `json:"device_id"`
	// Config Store commit containing the intended configuration.
	IntendedConfigCommitId NullableString `json:"intended_config_commit_id,omitempty"`
	// Reason the backup workflow was started.
	Trigger TriggerEnum `json:"trigger"`
	// User that requested the backup.
	User NullableString `json:"user,omitempty"`
	// Domain of the user requesting the backup.
	UserDomain NullableString `json:"user_domain,omitempty"`
	// Identifier of the parent workflow, if any.
	WorkflowId NullableString `json:"workflow_id,omitempty"`
}

type _BackupInput BackupInput

// NewBackupInput instantiates a new BackupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupInput(deviceId string, trigger TriggerEnum) *BackupInput {
	this := BackupInput{}
	this.DeviceId = deviceId
	this.Trigger = trigger
	return &this
}

// NewBackupInputWithDefaults instantiates a new BackupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupInputWithDefaults() *BackupInput {
	this := BackupInput{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *BackupInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *BackupInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *BackupInput) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetIntendedConfigCommitId returns the IntendedConfigCommitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupInput) GetIntendedConfigCommitId() string {
	if o == nil || IsNil(o.IntendedConfigCommitId.Get()) {
		var ret string
		return ret
	}
	return *o.IntendedConfigCommitId.Get()
}

// GetIntendedConfigCommitIdOk returns a tuple with the IntendedConfigCommitId field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BackupInput) GetIntendedConfigCommitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntendedConfigCommitId.Get(), o.IntendedConfigCommitId.IsSet()
}

// HasIntendedConfigCommitId returns a boolean if a field has been set.
func (o *BackupInput) HasIntendedConfigCommitId() bool {
	if o != nil && o.IntendedConfigCommitId.IsSet() {
		return true
	}

	return false
}

// SetIntendedConfigCommitId gets a reference to the given NullableString and assigns it to the IntendedConfigCommitId field.
func (o *BackupInput) SetIntendedConfigCommitId(v string) {
	o.IntendedConfigCommitId.Set(&v)
}

// SetIntendedConfigCommitIdNil sets the value for IntendedConfigCommitId to be an explicit nil
func (o *BackupInput) SetIntendedConfigCommitIdNil() {
	o.IntendedConfigCommitId.Set(nil)
}

// UnsetIntendedConfigCommitId ensures that no value is present for IntendedConfigCommitId, not even an explicit nil
func (o *BackupInput) UnsetIntendedConfigCommitId() {
	o.IntendedConfigCommitId.Unset()
}

// GetTrigger returns the Trigger field value
func (o *BackupInput) GetTrigger() TriggerEnum {
	if o == nil {
		var ret TriggerEnum
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *BackupInput) GetTriggerOk() (*TriggerEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *BackupInput) SetTrigger(v TriggerEnum) {
	o.Trigger = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupInput) GetUser() string {
	if o == nil || IsNil(o.User.Get()) {
		var ret string
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BackupInput) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *BackupInput) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableString and assigns it to the User field.
func (o *BackupInput) SetUser(v string) {
	o.User.Set(&v)
}

// SetUserNil sets the value for User to be an explicit nil
func (o *BackupInput) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *BackupInput) UnsetUser() {
	o.User.Unset()
}

// GetUserDomain returns the UserDomain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupInput) GetUserDomain() string {
	if o == nil || IsNil(o.UserDomain.Get()) {
		var ret string
		return ret
	}
	return *o.UserDomain.Get()
}

// GetUserDomainOk returns a tuple with the UserDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BackupInput) GetUserDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserDomain.Get(), o.UserDomain.IsSet()
}

// HasUserDomain returns a boolean if a field has been set.
func (o *BackupInput) HasUserDomain() bool {
	if o != nil && o.UserDomain.IsSet() {
		return true
	}

	return false
}

// SetUserDomain gets a reference to the given NullableString and assigns it to the UserDomain field.
func (o *BackupInput) SetUserDomain(v string) {
	o.UserDomain.Set(&v)
}

// SetUserDomainNil sets the value for UserDomain to be an explicit nil
func (o *BackupInput) SetUserDomainNil() {
	o.UserDomain.Set(nil)
}

// UnsetUserDomain ensures that no value is present for UserDomain, not even an explicit nil
func (o *BackupInput) UnsetUserDomain() {
	o.UserDomain.Unset()
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupInput) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId.Get()) {
		var ret string
		return ret
	}
	return *o.WorkflowId.Get()
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BackupInput) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkflowId.Get(), o.WorkflowId.IsSet()
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *BackupInput) HasWorkflowId() bool {
	if o != nil && o.WorkflowId.IsSet() {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given NullableString and assigns it to the WorkflowId field.
func (o *BackupInput) SetWorkflowId(v string) {
	o.WorkflowId.Set(&v)
}

// SetWorkflowIdNil sets the value for WorkflowId to be an explicit nil
func (o *BackupInput) SetWorkflowIdNil() {
	o.WorkflowId.Set(nil)
}

// UnsetWorkflowId ensures that no value is present for WorkflowId, not even an explicit nil
func (o *BackupInput) UnsetWorkflowId() {
	o.WorkflowId.Unset()
}

func (o BackupInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	if o.IntendedConfigCommitId.IsSet() {
		toSerialize["intended_config_commit_id"] = o.IntendedConfigCommitId.Get()
	}
	toSerialize["trigger"] = o.Trigger
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	if o.UserDomain.IsSet() {
		toSerialize["user_domain"] = o.UserDomain.Get()
	}
	if o.WorkflowId.IsSet() {
		toSerialize["workflow_id"] = o.WorkflowId.Get()
	}
	return toSerialize, nil
}

func (o *BackupInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_id": false,
		"trigger":   false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupInput := _BackupInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupInput)

	if err != nil {
		return err
	}

	*o = BackupInput(varBackupInput)

	return err
}

type NullableBackupInput struct {
	value *BackupInput
	isSet bool
}

func (v NullableBackupInput) Get() *BackupInput {
	return v.value
}

func (v *NullableBackupInput) Set(val *BackupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupInput(val *BackupInput) *NullableBackupInput {
	return &NullableBackupInput{value: val, isSet: true}
}

func (v NullableBackupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
