/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SiteCableValidationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteCableValidationInput{}

// SiteCableValidationInput Input for Site Cable Validation Workflow.
type SiteCableValidationInput struct {
	DeviceTypeIds   []string `json:"device_type_ids,omitempty"`
	RaiseForInvalid *bool    `json:"raise_for_invalid,omitempty"`
	Roles           []string `json:"roles,omitempty"`
	Site            string   `json:"site"`
	Status          []string `json:"status,omitempty"`
	Tenant          *string  `json:"tenant,omitempty"`
}

type _SiteCableValidationInput SiteCableValidationInput

// NewSiteCableValidationInput instantiates a new SiteCableValidationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteCableValidationInput(site string) *SiteCableValidationInput {
	this := SiteCableValidationInput{}
	var raiseForInvalid bool = false
	this.RaiseForInvalid = &raiseForInvalid
	this.Site = site
	var tenant string = "nsv"
	this.Tenant = &tenant
	return &this
}

// NewSiteCableValidationInputWithDefaults instantiates a new SiteCableValidationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteCableValidationInputWithDefaults() *SiteCableValidationInput {
	this := SiteCableValidationInput{}
	var raiseForInvalid bool = false
	this.RaiseForInvalid = &raiseForInvalid
	var tenant string = "nsv"
	this.Tenant = &tenant
	return &this
}

// GetDeviceTypeIds returns the DeviceTypeIds field value if set, zero value otherwise.
func (o *SiteCableValidationInput) GetDeviceTypeIds() []string {
	if o == nil || IsNil(o.DeviceTypeIds) {
		var ret []string
		return ret
	}
	return o.DeviceTypeIds
}

// GetDeviceTypeIdsOk returns a tuple with the DeviceTypeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SiteCableValidationInput) GetDeviceTypeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeviceTypeIds) {
		return nil, false
	}
	return o.DeviceTypeIds, true
}

// HasDeviceTypeIds returns a boolean if a field has been set.
func (o *SiteCableValidationInput) HasDeviceTypeIds() bool {
	if o != nil && !IsNil(o.DeviceTypeIds) {
		return true
	}

	return false
}

// SetDeviceTypeIds gets a reference to the given []string and assigns it to the DeviceTypeIds field.
func (o *SiteCableValidationInput) SetDeviceTypeIds(v []string) {
	o.DeviceTypeIds = v
}

// GetRaiseForInvalid returns the RaiseForInvalid field value if set, zero value otherwise.
func (o *SiteCableValidationInput) GetRaiseForInvalid() bool {
	if o == nil || IsNil(o.RaiseForInvalid) {
		var ret bool
		return ret
	}
	return *o.RaiseForInvalid
}

// GetRaiseForInvalidOk returns a tuple with the RaiseForInvalid field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SiteCableValidationInput) GetRaiseForInvalidOk() (*bool, bool) {
	if o == nil || IsNil(o.RaiseForInvalid) {
		return nil, false
	}
	return o.RaiseForInvalid, true
}

// HasRaiseForInvalid returns a boolean if a field has been set.
func (o *SiteCableValidationInput) HasRaiseForInvalid() bool {
	if o != nil && !IsNil(o.RaiseForInvalid) {
		return true
	}

	return false
}

// SetRaiseForInvalid gets a reference to the given bool and assigns it to the RaiseForInvalid field.
func (o *SiteCableValidationInput) SetRaiseForInvalid(v bool) {
	o.RaiseForInvalid = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *SiteCableValidationInput) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SiteCableValidationInput) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *SiteCableValidationInput) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *SiteCableValidationInput) SetRoles(v []string) {
	o.Roles = v
}

// GetSite returns the Site field value
func (o *SiteCableValidationInput) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *SiteCableValidationInput) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *SiteCableValidationInput) SetSite(v string) {
	o.Site = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SiteCableValidationInput) GetStatus() []string {
	if o == nil || IsNil(o.Status) {
		var ret []string
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SiteCableValidationInput) GetStatusOk() ([]string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SiteCableValidationInput) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []string and assigns it to the Status field.
func (o *SiteCableValidationInput) SetStatus(v []string) {
	o.Status = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *SiteCableValidationInput) GetTenant() string {
	if o == nil || IsNil(o.Tenant) {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SiteCableValidationInput) GetTenantOk() (*string, bool) {
	if o == nil || IsNil(o.Tenant) {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *SiteCableValidationInput) HasTenant() bool {
	if o != nil && !IsNil(o.Tenant) {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *SiteCableValidationInput) SetTenant(v string) {
	o.Tenant = &v
}

func (o SiteCableValidationInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteCableValidationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceTypeIds) {
		toSerialize["device_type_ids"] = o.DeviceTypeIds
	}
	if !IsNil(o.RaiseForInvalid) {
		toSerialize["raise_for_invalid"] = o.RaiseForInvalid
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	toSerialize["site"] = o.Site
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Tenant) {
		toSerialize["tenant"] = o.Tenant
	}
	return toSerialize, nil
}

func (o *SiteCableValidationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"site": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSiteCableValidationInput := _SiteCableValidationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSiteCableValidationInput)

	if err != nil {
		return err
	}

	*o = SiteCableValidationInput(varSiteCableValidationInput)

	return err
}

type NullableSiteCableValidationInput struct {
	value *SiteCableValidationInput
	isSet bool
}

func (v NullableSiteCableValidationInput) Get() *SiteCableValidationInput {
	return v.value
}

func (v *NullableSiteCableValidationInput) Set(val *SiteCableValidationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteCableValidationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteCableValidationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteCableValidationInput(val *SiteCableValidationInput) *NullableSiteCableValidationInput {
	return &NullableSiteCableValidationInput{value: val, isSet: true}
}

func (v NullableSiteCableValidationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteCableValidationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
