query auto_dhcp_subnets {
  prefixes(tags: ["dhcp-subnet"]) {
    id
    prefix
    ip_version
    rel_prefix_to_gateway {
      address
    }
  }
  pool_ips: ip_addresses(tags: ["dhcp-pool"]) {
    address
    ip_version
    parent {
      id
    }
    interfaces {
      name
      mac_address
      role {
        name
      }
      device {
        id
        name
        serial
        platform {
          name
        }
        status {
          name
        }
        configmanagerdevicestatus {
          ztp_enabled
          is_aggregate_managed
        }
      }
    }
  }
  reserved_ips: ip_addresses(tags: ["dhcp-reserve"]) {
    address
    ip_version
    parent {
      id
    }
    interfaces {
      name
      mac_address
      role {
        name
      }
      device {
        id
        name
        serial
        platform {
          name
        }
        status {
          name
        }
        configmanagerdevicestatus {
          ztp_enabled
          is_aggregate_managed
        }
      }
    }
  }
}