topology_path: ''
mock_blueprint: spx-fabric-demo
deployment_name: spx-fabric-demo
simulation_name: nv-config-manager-spx-fabric
oob_server_name: oob-mgmt-server
server_mode: use-existing
attach_switch: ''
attach_interface: ''
auto_configure: true
config_manager_repo: https://github.com/NVIDIA/nv-config-manager
config_manager_ref: main
size: small
cumulus_version: ''
deploy: true
run_mock_topology_job: true
mock_topology_path: development/mock_topology
template_plugin_paths:
- development/air_sim/template_plugins/superpod-template-plugin
extra_job_paths: []
extra_run_after_deploy: []
use_internal: false
wait_timeout: 1800
deploy_timeout: 3600
no_aggressive_dhcp: false
no_reset_before_dhcp: false
