/*
ZTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// FirmwareAPIService FirmwareAPI service
type FirmwareAPIService service

type ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest struct {
	ctx        context.Context
	ApiService *FirmwareAPIService
	platform   string
	version    string
}

func (r ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest) Execute() (*ChecksumResponse, *http.Response, error) {
	return r.ApiService.LoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetExecute(r)
}

/*
LoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGet Load Firmware Checksum

Load the firmware checksum by platform and version.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param platform
	@param version
	@return ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest
*/
func (a *FirmwareAPIService) LoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGet(ctx context.Context, platform string, version string) ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest {
	return ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest{
		ApiService: a,
		ctx:        ctx,
		platform:   platform,
		version:    version,
	}
}

// Execute executes the request
//
//	@return ChecksumResponse
func (a *FirmwareAPIService) LoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetExecute(r ApiLoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGetRequest) (*ChecksumResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ChecksumResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FirmwareAPIService.LoadFirmwareChecksumV1FirmwarePlatformVersionChecksumGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/firmware/{platform}/{version}/checksum"
	localVarPath = strings.Replace(localVarPath, "{"+"platform"+"}", url.PathEscape(parameterValueToString(r.platform, "platform")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest struct {
	ctx        context.Context
	ApiService *FirmwareAPIService
	platform   string
	version    string
}

func (r ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.LoadFirmwareV1FirmwarePlatformVersionGetExecute(r)
}

/*
LoadFirmwareV1FirmwarePlatformVersionGet Load Firmware

Load the firmware by platform and version.

Note: For large firmware files, use curl or direct browser download instead of
the OpenAPI UI, which may not handle large streaming responses properly.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param platform
	@param version
	@return ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest
*/
func (a *FirmwareAPIService) LoadFirmwareV1FirmwarePlatformVersionGet(ctx context.Context, platform string, version string) ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest {
	return ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest{
		ApiService: a,
		ctx:        ctx,
		platform:   platform,
		version:    version,
	}
}

// Execute executes the request
func (a *FirmwareAPIService) LoadFirmwareV1FirmwarePlatformVersionGetExecute(r ApiLoadFirmwareV1FirmwarePlatformVersionGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FirmwareAPIService.LoadFirmwareV1FirmwarePlatformVersionGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/firmware/{platform}/{version}"
	localVarPath = strings.Replace(localVarPath, "{"+"platform"+"}", url.PathEscape(parameterValueToString(r.platform, "platform")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"version"+"}", url.PathEscape(parameterValueToString(r.version, "version")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
