/*
ZTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"time"
)

// LastModified Last modification timestamp
type LastModified struct {
	Float32  *float32
	TimeTime *time.Time
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *LastModified) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into TimeTime
	err = json.Unmarshal(data, &dst.TimeTime)
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			return nil // data stored in dst.TimeTime, return on the first match
		}
	} else {
		dst.TimeTime = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(LastModified)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LastModified) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableLastModified struct {
	value *LastModified
	isSet bool
}

func (v NullableLastModified) Get() *LastModified {
	return v.value
}

func (v *NullableLastModified) Set(val *LastModified) {
	v.value = val
	v.isSet = true
}

func (v NullableLastModified) IsSet() bool {
	return v.isSet
}

func (v *NullableLastModified) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLastModified(val *LastModified) *NullableLastModified {
	return &NullableLastModified{value: val, isSet: true}
}

func (v NullableLastModified) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLastModified) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
