/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PoolUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolUsage{}

// PoolUsage Current allocation statistics for a configured IPv4 pool.
type PoolUsage struct {
	Assigned    int32   `json:"assigned"`
	Pool        string  `json:"pool"`
	Subnet      string  `json:"subnet"`
	SubnetId    int32   `json:"subnet_id"`
	Total       int32   `json:"total"`
	Utilization float32 `json:"utilization"`
}

type _PoolUsage PoolUsage

// NewPoolUsage instantiates a new PoolUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolUsage(assigned int32, pool string, subnet string, subnetId int32, total int32, utilization float32) *PoolUsage {
	this := PoolUsage{}
	this.Assigned = assigned
	this.Pool = pool
	this.Subnet = subnet
	this.SubnetId = subnetId
	this.Total = total
	this.Utilization = utilization
	return &this
}

// NewPoolUsageWithDefaults instantiates a new PoolUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolUsageWithDefaults() *PoolUsage {
	this := PoolUsage{}
	return &this
}

// GetAssigned returns the Assigned field value
func (o *PoolUsage) GetAssigned() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Assigned
}

// GetAssignedOk returns a tuple with the Assigned field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetAssignedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Assigned, true
}

// SetAssigned sets field value
func (o *PoolUsage) SetAssigned(v int32) {
	o.Assigned = v
}

// GetPool returns the Pool field value
func (o *PoolUsage) GetPool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pool
}

// GetPoolOk returns a tuple with the Pool field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetPoolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pool, true
}

// SetPool sets field value
func (o *PoolUsage) SetPool(v string) {
	o.Pool = v
}

// GetSubnet returns the Subnet field value
func (o *PoolUsage) GetSubnet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subnet
}

// GetSubnetOk returns a tuple with the Subnet field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetSubnetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subnet, true
}

// SetSubnet sets field value
func (o *PoolUsage) SetSubnet(v string) {
	o.Subnet = v
}

// GetSubnetId returns the SubnetId field value
func (o *PoolUsage) GetSubnetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SubnetId
}

// GetSubnetIdOk returns a tuple with the SubnetId field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetSubnetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubnetId, true
}

// SetSubnetId sets field value
func (o *PoolUsage) SetSubnetId(v int32) {
	o.SubnetId = v
}

// GetTotal returns the Total field value
func (o *PoolUsage) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PoolUsage) SetTotal(v int32) {
	o.Total = v
}

// GetUtilization returns the Utilization field value
func (o *PoolUsage) GetUtilization() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Utilization
}

// GetUtilizationOk returns a tuple with the Utilization field value
// and a boolean to check if the value has been set.
func (o *PoolUsage) GetUtilizationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Utilization, true
}

// SetUtilization sets field value
func (o *PoolUsage) SetUtilization(v float32) {
	o.Utilization = v
}

func (o PoolUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assigned"] = o.Assigned
	toSerialize["pool"] = o.Pool
	toSerialize["subnet"] = o.Subnet
	toSerialize["subnet_id"] = o.SubnetId
	toSerialize["total"] = o.Total
	toSerialize["utilization"] = o.Utilization
	return toSerialize, nil
}

func (o *PoolUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"assigned":    false,
		"pool":        false,
		"subnet":      false,
		"subnet_id":   false,
		"total":       false,
		"utilization": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolUsage := _PoolUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolUsage)

	if err != nil {
		return err
	}

	*o = PoolUsage(varPoolUsage)

	return err
}

type NullablePoolUsage struct {
	value *PoolUsage
	isSet bool
}

func (v NullablePoolUsage) Get() *PoolUsage {
	return v.value
}

func (v *NullablePoolUsage) Set(val *PoolUsage) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolUsage) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolUsage(val *PoolUsage) *NullablePoolUsage {
	return &NullablePoolUsage{value: val, isSet: true}
}

func (v NullablePoolUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
