/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LeaseDashboardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaseDashboardResponse{}

// LeaseDashboardResponse Lease, reservation, and pool summary used by the dashboard.
type LeaseDashboardResponse struct {
	ActiveLeaseCount int32 `json:"active_lease_count"`
	PoolCount        int32 `json:"pool_count"`
	ReservationCount int32 `json:"reservation_count"`
}

type _LeaseDashboardResponse LeaseDashboardResponse

// NewLeaseDashboardResponse instantiates a new LeaseDashboardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaseDashboardResponse(activeLeaseCount int32, poolCount int32, reservationCount int32) *LeaseDashboardResponse {
	this := LeaseDashboardResponse{}
	this.ActiveLeaseCount = activeLeaseCount
	this.PoolCount = poolCount
	this.ReservationCount = reservationCount
	return &this
}

// NewLeaseDashboardResponseWithDefaults instantiates a new LeaseDashboardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaseDashboardResponseWithDefaults() *LeaseDashboardResponse {
	this := LeaseDashboardResponse{}
	return &this
}

// GetActiveLeaseCount returns the ActiveLeaseCount field value
func (o *LeaseDashboardResponse) GetActiveLeaseCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveLeaseCount
}

// GetActiveLeaseCountOk returns a tuple with the ActiveLeaseCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetActiveLeaseCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveLeaseCount, true
}

// SetActiveLeaseCount sets field value
func (o *LeaseDashboardResponse) SetActiveLeaseCount(v int32) {
	o.ActiveLeaseCount = v
}

// GetPoolCount returns the PoolCount field value
func (o *LeaseDashboardResponse) GetPoolCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolCount
}

// GetPoolCountOk returns a tuple with the PoolCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetPoolCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolCount, true
}

// SetPoolCount sets field value
func (o *LeaseDashboardResponse) SetPoolCount(v int32) {
	o.PoolCount = v
}

// GetReservationCount returns the ReservationCount field value
func (o *LeaseDashboardResponse) GetReservationCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservationCount
}

// GetReservationCountOk returns a tuple with the ReservationCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetReservationCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservationCount, true
}

// SetReservationCount sets field value
func (o *LeaseDashboardResponse) SetReservationCount(v int32) {
	o.ReservationCount = v
}

func (o LeaseDashboardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaseDashboardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_lease_count"] = o.ActiveLeaseCount
	toSerialize["pool_count"] = o.PoolCount
	toSerialize["reservation_count"] = o.ReservationCount
	return toSerialize, nil
}

func (o *LeaseDashboardResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"active_lease_count": false,
		"pool_count":         false,
		"reservation_count":  false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeaseDashboardResponse := _LeaseDashboardResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeaseDashboardResponse)

	if err != nil {
		return err
	}

	*o = LeaseDashboardResponse(varLeaseDashboardResponse)

	return err
}

type NullableLeaseDashboardResponse struct {
	value *LeaseDashboardResponse
	isSet bool
}

func (v NullableLeaseDashboardResponse) Get() *LeaseDashboardResponse {
	return v.value
}

func (v *NullableLeaseDashboardResponse) Set(val *LeaseDashboardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaseDashboardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaseDashboardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaseDashboardResponse(val *LeaseDashboardResponse) *NullableLeaseDashboardResponse {
	return &NullableLeaseDashboardResponse{value: val, isSet: true}
}

func (v NullableLeaseDashboardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaseDashboardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
