/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the LeaseDashboardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaseDashboardResponse{}

// LeaseDashboardResponse Reservation and pool summary used by the splash-page dashboard.
type LeaseDashboardResponse struct {
	ActiveLeaseCount     int32               `json:"active_lease_count"`
	AssignedAddressCount int32               `json:"assigned_address_count"`
	PoolAddressCount     int32               `json:"pool_address_count"`
	Pools                []PoolUsage         `json:"pools"`
	ReservationCount     int32               `json:"reservation_count"`
	Reservations         []ReservationRecord `json:"reservations"`
}

type _LeaseDashboardResponse LeaseDashboardResponse

// NewLeaseDashboardResponse instantiates a new LeaseDashboardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaseDashboardResponse(activeLeaseCount int32, assignedAddressCount int32, poolAddressCount int32, pools []PoolUsage, reservationCount int32, reservations []ReservationRecord) *LeaseDashboardResponse {
	this := LeaseDashboardResponse{}
	this.ActiveLeaseCount = activeLeaseCount
	this.AssignedAddressCount = assignedAddressCount
	this.PoolAddressCount = poolAddressCount
	this.Pools = pools
	this.ReservationCount = reservationCount
	this.Reservations = reservations
	return &this
}

// NewLeaseDashboardResponseWithDefaults instantiates a new LeaseDashboardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaseDashboardResponseWithDefaults() *LeaseDashboardResponse {
	this := LeaseDashboardResponse{}
	return &this
}

// GetActiveLeaseCount returns the ActiveLeaseCount field value
func (o *LeaseDashboardResponse) GetActiveLeaseCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveLeaseCount
}

// GetActiveLeaseCountOk returns a tuple with the ActiveLeaseCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetActiveLeaseCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveLeaseCount, true
}

// SetActiveLeaseCount sets field value
func (o *LeaseDashboardResponse) SetActiveLeaseCount(v int32) {
	o.ActiveLeaseCount = v
}

// GetAssignedAddressCount returns the AssignedAddressCount field value
func (o *LeaseDashboardResponse) GetAssignedAddressCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AssignedAddressCount
}

// GetAssignedAddressCountOk returns a tuple with the AssignedAddressCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetAssignedAddressCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssignedAddressCount, true
}

// SetAssignedAddressCount sets field value
func (o *LeaseDashboardResponse) SetAssignedAddressCount(v int32) {
	o.AssignedAddressCount = v
}

// GetPoolAddressCount returns the PoolAddressCount field value
func (o *LeaseDashboardResponse) GetPoolAddressCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolAddressCount
}

// GetPoolAddressCountOk returns a tuple with the PoolAddressCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetPoolAddressCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolAddressCount, true
}

// SetPoolAddressCount sets field value
func (o *LeaseDashboardResponse) SetPoolAddressCount(v int32) {
	o.PoolAddressCount = v
}

// GetPools returns the Pools field value
func (o *LeaseDashboardResponse) GetPools() []PoolUsage {
	if o == nil {
		var ret []PoolUsage
		return ret
	}

	return o.Pools
}

// GetPoolsOk returns a tuple with the Pools field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetPoolsOk() ([]PoolUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pools, true
}

// SetPools sets field value
func (o *LeaseDashboardResponse) SetPools(v []PoolUsage) {
	o.Pools = v
}

// GetReservationCount returns the ReservationCount field value
func (o *LeaseDashboardResponse) GetReservationCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservationCount
}

// GetReservationCountOk returns a tuple with the ReservationCount field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetReservationCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservationCount, true
}

// SetReservationCount sets field value
func (o *LeaseDashboardResponse) SetReservationCount(v int32) {
	o.ReservationCount = v
}

// GetReservations returns the Reservations field value
func (o *LeaseDashboardResponse) GetReservations() []ReservationRecord {
	if o == nil {
		var ret []ReservationRecord
		return ret
	}

	return o.Reservations
}

// GetReservationsOk returns a tuple with the Reservations field value
// and a boolean to check if the value has been set.
func (o *LeaseDashboardResponse) GetReservationsOk() ([]ReservationRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reservations, true
}

// SetReservations sets field value
func (o *LeaseDashboardResponse) SetReservations(v []ReservationRecord) {
	o.Reservations = v
}

func (o LeaseDashboardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaseDashboardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_lease_count"] = o.ActiveLeaseCount
	toSerialize["assigned_address_count"] = o.AssignedAddressCount
	toSerialize["pool_address_count"] = o.PoolAddressCount
	toSerialize["pools"] = o.Pools
	toSerialize["reservation_count"] = o.ReservationCount
	toSerialize["reservations"] = o.Reservations
	return toSerialize, nil
}

func (o *LeaseDashboardResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"active_lease_count":     false,
		"assigned_address_count": false,
		"pool_address_count":     false,
		"pools":                  false,
		"reservation_count":      false,
		"reservations":           false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeaseDashboardResponse := _LeaseDashboardResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeaseDashboardResponse)

	if err != nil {
		return err
	}

	*o = LeaseDashboardResponse(varLeaseDashboardResponse)

	return err
}

type NullableLeaseDashboardResponse struct {
	value *LeaseDashboardResponse
	isSet bool
}

func (v NullableLeaseDashboardResponse) Get() *LeaseDashboardResponse {
	return v.value
}

func (v *NullableLeaseDashboardResponse) Set(val *LeaseDashboardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaseDashboardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaseDashboardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaseDashboardResponse(val *LeaseDashboardResponse) *NullableLeaseDashboardResponse {
	return &NullableLeaseDashboardResponse{value: val, isSet: true}
}

func (v NullableLeaseDashboardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaseDashboardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
