# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 4.2.28 on 2026-02-03 16:31

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_app_overlays", "0001_rename_from_fabric_partitions"),
        ("ipam", "0053_alter_vrfdeviceassignment_options_and_more"),
        ("extras", "0125_jobresult_date_started"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
        ("dcim", "0075_interface_duplex_interface_speed_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Overlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("isolation_type", models.CharField(max_length=50)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overlays",
                        to="dcim.location",
                    ),
                ),
                (
                    "route_targets",
                    models.ManyToManyField(blank=True, related_name="overlays", to="ipam.routetarget"),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overlays",
                        to="tenancy.tenant",
                    ),
                ),
                ("vlans", models.ManyToManyField(blank=True, related_name="overlays", to="ipam.vlan")),
                ("vrfs", models.ManyToManyField(blank=True, related_name="overlays", to="ipam.vrf")),
            ],
            options={
                "verbose_name": "Overlay",
                "verbose_name_plural": "Overlays",
                "ordering": ["name"],
                "unique_together": {("name", "location")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VXLAN",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "vnid",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(16777215),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vni_type", models.CharField(default="l2", max_length=10)),
                (
                    "l3_vlan_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4094),
                        ],
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="vxlans", to="ipam.namespace"
                    ),
                ),
                (
                    "overlay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vxlans",
                        to="nautobot_app_overlays.overlay",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vxlans",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vxlans",
                        to="ipam.vlan",
                    ),
                ),
                (
                    "vrf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vxlans",
                        to="ipam.vrf",
                    ),
                ),
            ],
            options={
                "verbose_name": "VXLAN",
                "verbose_name_plural": "VXLANs",
                "ordering": ["vnid"],
                "unique_together": {("vnid", "namespace")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OverlayAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("assigned_object_id", models.UUIDField()),
                ("role", models.CharField(blank=True, max_length=50)),
                (
                    "guid",
                    models.CharField(
                        blank=True,
                        help_text="InfiniBand port GUID (16-20 hex chars, e.g., '0002c903000e0b72')",
                        max_length=20,
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        blank=True,
                        help_text="PKey membership type override (defaults to PKey's membership_type if blank)",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_object_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ["device", "interface", "vrf", "vlan", "prefix"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "overlay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="nautobot_app_overlays.overlay",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
            ],
            options={
                "verbose_name": "Overlay Assignment",
                "verbose_name_plural": "Overlay Assignments",
                "ordering": ["overlay", "assigned_object_type", "assigned_object_id"],
                "unique_together": {("overlay", "assigned_object_type", "assigned_object_id")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InfiniBandPKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("pkey", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("membership_type", models.CharField(default="full", max_length=20)),
                ("qos_config", models.JSONField(blank=True, null=True)),
                (
                    "overlay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pkeys",
                        to="nautobot_app_overlays.overlay",
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="infiniband_pkeys",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "InfiniBand PKey",
                "verbose_name_plural": "InfiniBand PKeys",
                "ordering": ["pkey"],
                "unique_together": {("pkey", "overlay")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
